// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"app/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 查询题目详情
				Method:  http.MethodPost,
				Path:    "/api/question/list/page",
				Handler: getQuestionDetailHandler(serverCtx),
			},
			{
				// 获取题目列表
				Method:  http.MethodPost,
				Path:    "/api/question/list/page/vo",
				Handler: getQuestionListPageVoHandler(serverCtx),
			},
			{
				// 查询题目提交记录
				Method:  http.MethodPost,
				Path:    "/api/question/question_submit/list/page",
				Handler: getQuestionQuestionSubmitListPageHandler(serverCtx),
			},
			{
				// 获取用户登录信息
				Method:  http.MethodGet,
				Path:    "/api/user/get/login",
				Handler: getLoginUserHandler(serverCtx),
			},
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/api/user/login",
				Handler: loginHandler(serverCtx),
			},
		},
	)
}
