// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type GetLoginUserResp struct {
	CreateTime  string `json:"createTime,optional"`  // 创建时间
	Id          int64  `json:"id,optional"`          // 用户ID
	UpdateTime  string `json:"updateTime,optional"`  // 更新时间
	UserAvatar  string `json:"userAvatar,optional"`  // 用户头像
	UserName    string `json:"userName,optional"`    // 用户名
	UserProfile string `json:"userProfile,optional"` // 用户简介
	UserRole    string `json:"userRole,optional"`    // 用户角色
}

type JudgeConfig struct {
	MemoryLimit int `json:"memoryLimit,optional"` // 内存限制（单位：MB）
	StackLimit  int `json:"stackLimit,optional"`  // 栈空间限制（单位：KB）
	TimeLimit   int `json:"timeLimit,optional"`   // 时间限制（单位：ms）
}

type JudgeInfo struct {
	Memory  int    `json:"memory,optional"`  // 内存使用（单位：MB）
	Message string `json:"message,optional"` // 判题结果信息
	Time    int    `json:"time,optional"`    // 时间使用（单位：ms）
}

type LoginReq struct {
	UserAccount  string `json:"userAccount"`
	UserPassword string `json:"userPassword"`
}

type LoginResp struct {
	ID          int    `json:"id,optional"`          // 用户ID
	UserAccount string `json:"userAccount,optional"` // 用户账号
	UserName    string `json:"userName,optional"`    // 用户名
	UserProfile string `json:"userProfile,optional"` // 用户简介
	UserRole    string `json:"userRole,optional"`    // 用户角色
	CreateTime  string `json:"createTime,optional"`  // 创建时间
	UpdateTime  string `json:"updateTime,optional"`  // 更新时间
	UserAvatar  string `json:"userAvatar,optional"`  // 用户头像
}

type OrderItem struct {
	Column string `json:"column,optional"` // 排序字段
	Asc    bool   `json:"asc,optional"`    // 是否升序
}

type PageQuestionResq struct {
	CountId          string      `json:"countId,optional"`          // 计数ID
	Current          int         `json:"current,optional"`          // 当前页码
	MaxLimit         int         `json:"maxLimit,optional"`         // 最大限制
	OptimizeCountSql bool        `json:"optimizeCountSql,optional"` // 是否优化计数SQL
	Orders           []OrderItem `json:"orders,optional"`           // 排序项
	Pages            int         `json:"pages,optional"`            // 总页数
	Records          []Question  `json:"records,optional"`          // 题目列表
	SearchCount      bool        `json:"searchCount,optional"`      // 是否搜索计数
	Size             int         `json:"size,optional"`             // 每页大小
	Total            int         `json:"total,optional"`            // 总记录数
}

type PageQuestionSubmitVOResp struct {
	CountId          string             `json:"countId,optional"`          // 计数ID
	Current          int                `json:"current,optional"`          // 当前页码
	MaxLimit         int                `json:"maxLimit,optional"`         // 最大限制
	OptimizeCountSql bool               `json:"optimizeCountSql,optional"` // 是否优化计数SQL
	Orders           []OrderItem        `json:"orders,optional"`           // 排序项
	Pages            int                `json:"pages,optional"`            // 总页数
	Records          []QuestionSubmitVO `json:"records,optional"`          // 提交记录列表
	SearchCount      bool               `json:"searchCount,optional"`      // 是否搜索计数
	Size             int                `json:"size,optional"`             // 每页大小
	Total            int                `json:"total,optional"`            // 总记录数
}

type Question struct {
	AcceptedNum int    `json:"acceptedNum,optional"` // 通过次数
	Answer      string `json:"answer,optional"`      // 答案
	Content     string `json:"content,optional"`     // 题目内容
	CreateTime  string `json:"createTime,optional"`  // 创建时间
	FavourNum   int    `json:"favourNum,optional"`   // 收藏次数
	Id          int    `json:"id,optional"`          // 题目ID
	IsDelete    int    `json:"isDelete,optional"`    // 是否删除（标记）
	JudgeCase   string `json:"judgeCase,optional"`   // 判题用例
	JudgeConfig string `json:"judgeConfig,optional"` // 判题配置
	SubmitNum   int    `json:"submitNum,optional"`   // 提交次数
	Tags        string `json:"tags,optional"`        // 标签（逗号分隔）
	ThumbNum    int    `json:"thumbNum,optional"`    // 点赞次数
	Title       string `json:"title,optional"`       // 题目标题
	UpdateTime  string `json:"updateTime,optional"`  // 更新时间
	UserId      int    `json:"userId,optional"`      // 用户ID
}

type QuestionListResp struct {
	CountId          string       `json:"countId,optional"`          // 计数ID
	Current          int          `json:"current,optional"`          // 当前页码
	MaxLimit         int          `json:"maxLimit,optional"`         // 最大限制
	OptimizeCountSql bool         `json:"optimizeCountSql,optional"` // 是否优化计数SQL
	Orders           []OrderItem  `json:"orders,optional"`           // 排序项
	Pages            int          `json:"pages,optional"`            // 总页数
	Records          []QuestionVO `json:"records,optional"`          // 问题列表
	SearchCount      bool         `json:"searchCount,optional"`      // 是否搜索计数
	Size             int          `json:"size,optional"`             // 每页大小
	Total            int          `json:"total,optional"`            // 总记录数
}

type QuestionQueryReq struct {
	Answer    string   `json:"answer,optional"`    // 答案
	Content   string   `json:"content,optional"`   // 内容
	Current   int      `json:"current,optional"`   // 当前页码
	Id        int      `json:"id,optional"`        // 问题ID
	PageSize  int      `json:"pageSize,optional"`  // 每页大小
	SortField string   `json:"sortField,optional"` // 排序字段
	SortOrder string   `json:"sortOrder,optional"` // 排序顺序
	Tags      []string `json:"tags,optional"`      // 标签
	Title     string   `json:"title,optional"`     // 标题
	UserId    int      `json:"userId,optional"`    // 用户ID
}

type QuestionQueryRequest struct {
	Answer    string   `json:"answer,optional"`    // 答案
	Content   string   `json:"content,optional"`   // 题目内容
	Current   int      `json:"current,optional"`   // 当前页码
	Id        int      `json:"id,optional"`        // 题目ID
	PageSize  int      `json:"pageSize,optional"`  // 每页大小
	SortField string   `json:"sortField,optional"` // 排序字段
	SortOrder string   `json:"sortOrder,optional"` // 排序顺序
	Tags      []string `json:"tags,optional"`      // 标签列表
	Title     string   `json:"title,optional"`     // 题目标题
	UserId    int      `json:"userId,optional"`    // 用户ID
}

type QuestionSubmitQueryRequest struct {
	Current    int    `json:"current,optional"`    // 当前页码
	Language   string `json:"language,optional"`   // 编程语言
	PageSize   int    `json:"pageSize,optional"`   // 每页大小
	QuestionId int    `json:"questionId,optional"` // 题目ID
	SortField  string `json:"sortField,optional"`  // 排序字段
	SortOrder  string `json:"sortOrder,optional"`  // 排序顺序
	Status     int    `json:"status,optional"`     // 提交状态
	UserId     int    `json:"userId,optional"`     // 用户ID
}

type QuestionSubmitVO struct {
	Code       string     `json:"code,optional"`       // 提交代码
	CreateTime string     `json:"createTime,optional"` // 创建时间
	Id         int        `json:"id,optional"`         // 提交记录ID
	JudgeInfo  JudgeInfo  `json:"judgeInfo,optional"`  // 判题信息
	Language   string     `json:"language,optional"`   // 编程语言
	QuestionId int        `json:"questionId,optional"` // 题目ID
	QuestionVO QuestionVO `json:"questionVO,optional"` // 题目信息
	Status     int        `json:"status,optional"`     // 提交状态
	UpdateTime string     `json:"updateTime,optional"` // 更新时间
	UserId     int        `json:"userId,optional"`     // 用户ID
	UserVO     UserVO     `json:"userVO,optional"`     // 用户信息
}

type QuestionVO struct {
	AcceptedNum int         `json:"acceptedNum,optional"` // 通过次数
	Content     string      `json:"content,optional"`     // 问题内容
	CreateTime  string      `json:"createTime,optional"`  // 创建时间
	FavourNum   int         `json:"favourNum,optional"`   // 收藏次数
	Id          int         `json:"id,optional"`          // 问题ID
	JudgeConfig JudgeConfig `json:"judgeConfig,optional"` // 判题配置
	SubmitNum   int         `json:"submitNum,optional"`   // 提交次数
	Tags        []string    `json:"tags,optional"`        // 问题标签
	ThumbNum    int         `json:"thumbNum,optional"`    // 点赞次数
	Title       string      `json:"title,optional"`       // 问题标题
	UpdateTime  string      `json:"updateTime,optional"`  // 更新时间
	UserId      int         `json:"userId,optional"`      // 用户ID
	UserVO      UserVO      `json:"userVO,optional"`      // 用户信息
}

type UserVO struct {
	CreateTime  string `json:"createTime,optional"`  // 创建时间
	Id          int    `json:"id,optional"`          // 用户ID
	UserAvatar  string `json:"userAvatar,optional"`  // 用户头像
	UserName    string `json:"userName,optional"`    // 用户名
	UserProfile string `json:"userProfile,optional"` // 用户简介
	UserRole    string `json:"userRole,optional"`    // 用户角色
}
